@server=http://localhost:3000
@createdConnectionId={{createNewConnection.response.body.$.id}}

### GET all VPN connections
GET {{server}}/connections

### GET VPN connection by id
GET {{server}}/connections/1

### POST new VPN connection
# @name createNewConnection
POST {{server}}/connections
Content-Type: application/json

{
  "user": "Guilherme",
  "vpnIp": "10.8.0.2",
  "sourceIp": "192.168.56.10",
  "protocol": "OpenVPN",
  "status": "active",
  "traffic": "125 MB"
}

### PUT update VPN connection by id
PUT {{server}}/connections/{{createdConnectionId}}
Content-Type: application/json

{
  "user": "Guilherme",
  "vpnIp": "10.8.0.2",
  "sourceIp": "192.168.56.10",
  "protocol": "OpenVPN",
  "status": "inactive",
  "traffic": "310 MB"
}

### DELETE VPN connection by id
DELETE {{server}}/connections/{{createdConnectionId}}
